name: 'Setup esy.sh environment'
description: 'Setup your runner with esy.sh'
author: 'Elie at OCamlPro'
inputs: 
  sandbox:
    description: 'The file that describe the sandbox without .json'
    required: true
    default: 'package'
runs:
  using: 'node12'
  main: 
    - name: install esy
      run: npm install -g esy
    - name: Install dependencies
      run: esy "@${{ sandbox }}" install
    - name: Install dependencies
      run: esy "@${{ sandbox }}" build-dependencies
